StaticData.Tiks = [];
StaticData.TiksOrder = [];

	StaticData.Tiks[24] = [];
	StaticData.TiksOrder[24] = [];
		StaticData.Tiks[24][33] = "красноярск, железнодорожная";
		StaticData.TiksOrder[24][0] = 33;
		StaticData.Tiks[24][34] = "красноярск, кировская";
		StaticData.TiksOrder[24][1] = 34;
		StaticData.Tiks[24][35] = "красноярск, ленинская";
		StaticData.TiksOrder[24][2] = 35;
		StaticData.Tiks[24][36] = "красноярск, октябрьская";
		StaticData.TiksOrder[24][3] = 36;
		StaticData.Tiks[24][37] = "красноярск, свердловская";
		StaticData.TiksOrder[24][4] = 37;
		StaticData.Tiks[24][38] = "красноярск, советская";
		StaticData.TiksOrder[24][5] = 38;
		StaticData.Tiks[24][39] = "красноярск, центральная";
		StaticData.TiksOrder[24][6] = 39;