<?php
const PROJECT_GN = 'GN';
const PROJECT_GL = 'CL';
const PROJECT_ROSVYBORY = 'RV';
const PROJECT_GOLOS = 'AG';
const PROJECT_GRAKON = 'GR';
const PROJECT_SONAR = 'SN';
const PROJECT_LIGA = 'LI';
const PROJECT_SHTABPROHOROVA = 'MP';
const PROJECT_SMS_EXITPOLE = 'SE';
